##### This shows the use of Training and Validation datasets

In [14]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [34]:
data = range(52)
train = [x for x in data if x%2!=0]
test = [x for x in data if x%2==0]
len(train) == len(test)

True

In [41]:
batchSize=5
trainDS = tf.data.Dataset.from_tensor_slices(train)
trainDS = trainDS.shuffle(buffer_size=len(train)).batch(batchSize)
testDS = tf.data.Dataset.from_tensor_slices(test)
testDS = testDS.batch(batchSize)

In [42]:
iter = tf.data.Iterator.from_structure(trainDS.output_types, tf.compat.v1.data.get_output_shapes(trainDS))
batch = iter.get_next()

In [43]:
trainInit = iter.make_initializer(trainDS)
testInit = iter.make_initializer(testDS)

In [44]:
trainBatches = int(len(train)/batchSize)
print("Training:    {} batches of size {}".format(trainBatches, batchSize))
testBatches = int(len(test)/batchSize)
print("Validation: {} batches of size {}".format(testBatches, batchSize))

Training:    5 batches of size 5
Validation: 5 batches of size 5


In [45]:
epochs = 2
with tf.Session() as sess:
    for e in range(epochs):
        sess.run(trainInit)
        for _ in range(trainBatches):
            b = sess.run(batch)
            print(b)
        print("---")
        sess.run(testInit)
        for _ in range(testBatches):
            print(sess.run(batch))

[41  9 51  3  1]
[11 19 23 25 21]
[43  7 29 15 39]
[45 17 13 49 31]
[47 27 33 37 35]
---
[0 2 4 6 8]
[10 12 14 16 18]
[20 22 24 26 28]
[30 32 34 36 38]
[40 42 44 46 48]
[13  1 47 23 37]
[51  9 33 43 21]
[31 39 49  3 25]
[11 17 45 15  5]
[41 19 29  7 35]
---
[0 2 4 6 8]
[10 12 14 16 18]
[20 22 24 26 28]
[30 32 34 36 38]
[40 42 44 46 48]
